# -*- coding: utf-8 -*-
"""google map api

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZVsYR-e3MoA42AhKPXoSsBK5D-NR00l4
"""

#導入模組&設定憑證
import googlemaps
import time #python內建的時間模組後面設定間隔時間會用到
import numpy as np
import pandas as pd
center = ["若水國際", "中央大學", "台中車站", '高雄車站']
label = ["材料行", "餐廳","咖啡廳", "寵物店", '飲料店', "維修廠", "電器行", "小吃店", "早餐店", "學校", "企業"]
gmaps=googlemaps.Client(key="AIzaSyAq4Q1SKyzdcbvvwF0Wx8I8JSL195aTBwE")
f = open('./point.txt', 'w')
l = open('./locs.txt', 'w')
def nearby(word, loc, rad):
  ids = []
  results = []
  #用gmaps.places_radar這個代碼來查total有幾個結果
  query_result = gmaps.places_nearby(keyword=word,location=loc, radius=rad)
  results.extend(query_result['results'])
  while query_result.get('next_page_token'):
    time.sleep(2)
    query_result = gmaps.places_nearby(page_token=query_result['next_page_token'])
    results.extend(query_result['results'])    
    for place in results:
      ids.append(place['place_id'])
  return ids

stations = []
locs = []
rad = 50000
for i in center:
  #取得地理編碼
  geocode_result = gmaps.geocode(i)
  loc = geocode_result[0]['geometry']['location']
  locs.append(geocode_result[0]['geometry']['location'])
  f.write(i+'\n')
  station = nearby('車站', loc, rad)
  print("找到以"+i+"為中心半徑"+str(rad)+"公尺的車站數量(google mapi api上限提供60間): "+str(len(station)))
  stations = station + stations
  #station = nearby('捷運', loc, rad)
  #print("找到以"+i+"為中心半徑"+str(rad)+"公尺的捷運數量(google mapi api上限提供60間): "+str(len(station)))
  stations = station + stations
stores_info = []
# 去除重複id
stations = list(set(stations))
print(len(stations)) 
for id in stations:
  point_data = gmaps.place(place_id=id, language='zh-TW')
  stores_info.append(point_data['result'])
  locs.append(point_data['result']['geometry']['location'])
  center.append(point_data['result']['name'])
  l.writelines(id+'\n')
  f.write(point_data['result']['name']+'\n')
output = pd.DataFrame.from_dict(stores_info)

for i in range(len(locs)):
  for j in label:
    station = nearby(j, locs[i], 5000)
    print("找到以"+center[i]+"為中心半徑"+str(5000)+"公尺的"+j+"數量(google mapi api上限提供60間): "+str(len(station)))
    stations = station + stations
stores_info = []
# 去除重複id
stations = list(set(stations))
print(len(stations)) 
for id in stations:
  point_data = gmaps.place(place_id=id, language='zh-TW')
  stores_info.append(point_data['result'])
  locs.append(point_data['result']['geometry']['location'])
  center.append(point_data['result']['name'])
  l.write(id+'\n')
  f.write(point_data['result']['name']+'\n')
output = pd.DataFrame.from_dict(stores_info)
f.close()
l.close()